version: '3.1'

services:
  mysql:
    image: mysql
    container_name: development_database
    platform: linux/amd64 #because i use M1
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: isd-db
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: admin
    ports:
      - 3309:3306
    volumes:
      - /docker-entrypoint-initdb.d
      - development-mysql-data:/var/lib/mysql
  
  mysql2:
    image: mysql
    container_name: test_database
    platform: linux/amd64 #because i use M1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: isd-db-test
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: admin
    ports:
      - 3310:3306
    volumes:
      - /docker-entrypoint-initdb.d
      - test-mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  development-mysql-data:
  test-mysql-data: