service: zgt

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# custom:
#   serverlessPluginTypescript:
#     tsConfigFileLocation: './tsconfig.json'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-express   

package:
  include:
    - ./src

functions:
  healthCheck:
    handler: src/app.handler
    events: 
     - httpApi:
          path: /api/v1/health
          method: GET
     - httpApi:
          path: /api/v1/lead/all
          method: GET 
     - httpApi:
          path: /api/v1/lead/create
          method: POST 
     - httpApi:
          path: /api/v1/lead/all
          method: DELETE
     - httpApi:
          path: /api/v1/lead/{lead_id}
          method: DELETE
     - httpApi:
          path: /api/v1/lead/submit_request
          method: POST 
    environment:
      NODE_ENV: 'development'